source 'https://github.com/CocoaPods/Specs.git'

target 'BMInputBox', :exclusive => true do
  pod "BMInputBox", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "BMInputBox", :path => "../"

  
end
